project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Yanshu Wang"
  site-url: https://wangyenshu.github.io/wangyanshu
  description: "Yanshu Wang's Academic Homepage"

  page-footer:
    left: ""
    right: ""

  navbar:
    left:
    
      - href: index.qmd
        text: Home
        
      - href: news/index.qmd
        text: News

      - href: publications/index.qmd
        text: Publications
        
      - href: presentations/index.qmd
        text: Presentations
        
      - href: projects/index.qmd
        text: Projects
      
      - href: teaching/index.qmd
        text: Teaching
        
      - href: CV/index.qmd
        text: CV

    right:
      
      - icon: rss
        href: index.xml
format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    
filters:
  - shinylive

execute:
  freeze: auto


